from django.conf.urls.defaults import *
from signup_app.views import activate, signup
from django.views.generic.simple import direct_to_template
from kwippyproject.kwippy.views import auth_views, static_views, auth_views_twitter
from kwippyproject.search_app.views import SearchFeed,AtomSearchFeed
from kwippyproject.feeds_app.RSSFeed import PublicTimelineFeed,ActivePublicTimelineFeed,FriendsTimelineFeed,ActiveFriendsTimelineFeed,UserTimelineFeed,RepliesFeed,FriendsFeed,FollowersFeed,FavoriteFeed
from kwippyproject.feeds_app.AtomFeed import AtomPublicTimelineFeed,ActiveAtomPublicTimelineFeed,AtomFriendsTimelineFeed,ActiveAtomFriendsTimelineFeed,AtomUserTimelineFeed,AtomRepliesFeed,AtomFriendsFeed,AtomFollowersFeed,AtomFavoriteFeed
from kwippy.models.quip import Quip
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from kwippyproject.allsitemaps import *

#sitemaps = {
#    'quip':QuipSitemap,
#    'profile':ProfileSitemap,
#}
urlpatterns = patterns('',
#     (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps})
     (r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/dipankar/others/kwippy/kwippyproject/public/images'}),
     (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/dipankar/others/kwippy/kwippyproject/public/css'}),
     (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/dipankar/others/kwippy/kwippyproject/public/js'}),
     (r'^comments/post/', 'kwippyproject.kwippy.views.comment.my_post_comment'),
     (r'^anon_comments/post/', 'kwippyproject.kwippy.views.comment.anon_comment'),                       
     (r'^comments/delete/([0-9]+)/$', 'kwippyproject.kwippy.views.comment.delete_comment'),
     (r'^comments/', include('django.contrib.comments.urls')),
#     (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
#     (r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
     (r'^robots.txt$', include('robots.urls')),
)
#Static Pages
urlpatterns += patterns('kwippyproject.kwippy.views',
     url(r'^help1/$', static_views.kwippy_help, name='help'),     
     url(r'^home/extras/$', static_views.extras, name='extra'),
     url(r'^home/tos/$', static_views.tos, name='tos'),
     url(r'^home/privacy/$', static_views.privacy, name='privacy'),
     url(r'^home/team/$', static_views.team, name='team'),
     url(r'^home/about/$', static_views.about, name='team'),
     url(r'^home/solutions/$', static_views.solutions, name='solutions'),
)
#URL Mappings to auth_views.py
urlpatterns += patterns('kwippyproject.kwippy.views',
     url(r'^login/$', auth_views.login, {'template_name': 'signup/login.html'}, name='auth_login'),
     url(r'^logout/$',auth_views.logout,{'template_name': 'signup/logged_out.html'}, name='auth_logout'),
     url(r'^password/change/$', auth_views.password_change, name='auth_password_change'),     
     url(r'^home/forgotpassword/$', auth_views.forgot_password, name='password_reset'),     
     url(r'^home/resetpassword/(?P<reset_link>\w+)/$', auth_views.reset_password, name='password_reset'),     
)

#URL Mappings to signup module
urlpatterns += patterns('',     
     url(r'^signup/(?P<invitation_hash>\w+)/$', signup,  name='signup_register'), (r'^accounts/', include('signup.urls')),
     url(r'^signup/complete/$', direct_to_template, {'template': 'signup/signup_complete.html'}, name='signup_complete'),
     url(r'^activate/(?P<activation_key>\w+)/$', activate, name='signup_activate'),
)

#URL Mappings to console module
urlpatterns += patterns('kwippyproject.console_app',
     url(r'^console/$',                                           'views.main_view'),
     url(r'^console/averages/$',                                  'views.averages'),                        
     url(r'^console/integrateim/$',                               'views.integrate_im'),
     url(r'^console/mailer/$',                                    'views.mail_all'),
     url(r'^console/featuring/$',                                 'views.featuring'),
     url(r'^console/toppers/$',                                   'views.toppers'),
     url(r'^console/topper_kwips/$',                              'views.topper_kwips'),
     url(r'^console/popular_kwips/$',                              'views.popular_kwips'),        
     url(r'^console/invitations/$',                               'views.invitation'),
     url(r'^console/twittervirality/$',                           'views.twittervirality'),
     url(r'^console/dailytwittervirality/$',                           'views.dailytwittervirality'),                        
     url(r'^console/virality/$',                                  'views.virality'),
     url(r'^console/guestpass/$',                                 'views.day_wise_acivity'),
     url(r'^console/featured_users/$',                            'views.featured_users'),
     url(r'^console/feature_new_users/$',                         'views.feature_new_users'),
     url(r'^console/daily_logins/$',                              'views.day_wise_logins'),                        
     url(r'^console/daily_comments/$',                            'views.day_wise_comments'),
     url(r'^console/daily_pms/$',                                 'views.day_wise_pms'),
     url(r'^console/daily_follows/$',                             'views.daily_follows'),                        
     url(r'^console/daily_favorites/$',                           'views.day_wise_favorites'),                        
     url(r'^console/daily_commenters/$',                          'views.day_wise_commenters'),
     url(r'^console/weekly_commenters/$',                         'views.unique_weekly_commenters'),
     url(r'^console/daily_commentedons/$',                        'views.day_wise_commentedons'),
     url(r'^console/daily_betainvites/$',                         'views.day_wise_betainvites'),            
     url(r'^console/day_wise_convinvites/$',                      'views.day_wise_convinvites'),
     url(r'^console/last_loggedin_users/$',                       'views.last_logged_in_users'),
     url(r'^console/memcached/$',                                 'views.memcached_status'),
     url(r'^console/guppy/$',                                     'views.guppy_status'),
     url(r'^console/notifications/$',                             'views.notifications'),
     url(r'^console/agewise/$',                                   'views.agewise'),
     url(r'^console/birthdays/$',                                 'views.birthdays'),
     url(r'^console/mailfooter/$',                                'views.mailfooter'),
     url(r'^console/birthdaymails/$',                             'views.send_bday_email'),
     url(r'^console/comm_queue/$',                                'views.show_comm_queue'),
     url(r'^console/mail_log/$',                                  'views.show_email_log'),
     url(r'^console/rssuser/$',                                   'views.createRssUser'),
     url(r'^console/acc_delete/$',                                'views.acc_delete'),
     url(r'^console/anon_conv_mail_log/$',                        'views.show_anon_conv_invite_log'),     
     url(r'^console/roll_pendinginvites/$',                       'views.roll_pendinginvites'),                        
     url(r'^console/list/beta_emails/$',                          'views.listemail'),
     url(r'^console/list/invites_status/$',                       'views.invites_status'),
     url(r'^console/asdadasdadadasdasdasd/$',                     'views.send_pending_invites'),
     url(r'^reports/new_users/(\d{4})/([A-Za-z]+)/(\d{2})/$',     'team_views.new_users'),
     url(r'^reports/toppers/$',                                   'team_views.toppers'),                        
     url(r'^reports/inactive_users/$',                            'team_views.inactive_users'),                        
)
urlpatterns += patterns('kwippyproject.feedback_app',
     (r'^feedback/$',                                                 'views.main', {'fb_for':'all'}),
     (r'^feedback/self/$',                                             'views.main', {'fb_for':'self'}),
#    (r'^feedback/list',                                              'views.list'),
#    (r'^feedback/view/(?P<fb_id>\d+)/$',                             'views.single'),
#    (r'^console/feedback$',                                          'views.feature_feedback')
)
urlpatterns += patterns('kwippyproject.search_app',
     (r'^search/$',                                                   'views.user_search',{'filter':'created_at'}),
     (r'^search/active/$',                                            'views.user_search',{'filter':'last_comment_at'}),
)
        
rss_status_feeds = {
    'everyone' : PublicTimelineFeed,
    'everyoneactive' : ActivePublicTimelineFeed,    
    'networkactive' : ActiveFriendsTimelineFeed,
    'network' : FriendsTimelineFeed,    
    'kwips' : UserTimelineFeed,
    'favorites' : FavoriteFeed,
    'replies' : RepliesFeed,
    'search' : SearchFeed,
}
atom_status_feeds = {
    'everyone' : AtomPublicTimelineFeed,
    'everyoneactive' : ActiveAtomPublicTimelineFeed,    
    'networkactive' : ActiveAtomFriendsTimelineFeed,
    'network' : AtomFriendsTimelineFeed,
    'kwips' : AtomUserTimelineFeed,
    'favorites' : AtomFavoriteFeed,
    'replies' : AtomRepliesFeed,
    'search': AtomSearchFeed,
}
urlpatterns += patterns('',
     (r'^api/(?P<url>.*).rss','django.contrib.syndication.views.feed',{'feed_dict': rss_status_feeds}),
     (r'^api/(?P<url>.*).atom','django.contrib.syndication.views.feed',{'feed_dict': atom_status_feeds}),
)

urlpatterns += patterns('',
   url(r'^api/kwips/update.(json|xml)', 'kwippyproject.api_app.views.post_kwip'),
   (r'^api/sms/(?P<country_name>\w+)$',  'kwippyproject.api_app.views.post_sms'),  
)
urlpatterns += patterns('kwippyproject.kwippy.views',
     #(r'^$',                                                          'views.home'),
     #(r'^/$',                                                         'views.home'),
     (r'^$',                           'mykwips.everyones_kwips',{'filter':'active'}),
     (r'^/$',                           'mykwips.everyones_kwips',{'filter':'active'}),
     (r'^admin/$',                                                    'views.home'),
     (r'^home/$',                                                     'views.home'),
     (r'^dashboard/$',                                                'views.dashboard'),
     (r'^dashboard/import/$',                                         'views.dashboard'),
     (r'^dashboard/profile/$',                                        'views.dashboard_profile'),
     (r'^dashboard/account/$',                                        'views.dashboard_account'),
     (r'^dashboard/kwips_page/$',                                     'views.dashboard_kwips_page'),
     (r'^dashboard/invite/$',                                         'views.dashboard_invite'),
     #(r'^explore/$',                                                  'explore.main'),
     (r'^home/contactus/$',                                           'contact_us.contactus'),
     #(r'^signup/$',                                                   'views.home'),
     (r'^signup/$',                                                  'beta_invite.coming_soon'),             
     (r'^feedback/add/$',                                             'views.store_feedback'),
     (r'^friendships/(?P<offerer_username>\w+)/$',                    'friend.accept_deny_requests'),
     (r'^functions/$',                                                'misc.main_view'),
     (r'^functions/delete/$',                                         'misc.delete_duplicate_kwips'),
     #(r'^everyone/$',                                                 'mykwips.everyones_kwips'),
     (r'^everyone/geo/$',                                             'mykwips.everyones_kwips',{'filter':'geo'}),
     (r'^everyone/active/$',                                          'mykwips.everyones_kwips',{'filter':'active'}),     
     (r'^everyone/recent/$',                                          'mykwips.everyones_kwips',{'filter':''}),
     (r'^everyone/$',                                                 'mykwips.everyones_kwips',{'filter':'active'}),
     (r'^everyone/comments/$',                                        'mycomments.everyones_comments'),
     (r'^everyone/bookmarks/$',                                   'favorites.main',{'user_login':'everyone'}),
     (r'^everyone/featuredkwips/$',                                   'featured.main',),                        
     (r'^kwip/add/$',                                                 'mykwips.store_kwip'),
     (r'^kwip/favourite/(?P<quip_id>\d+)/$',                          'mykwips.favourite_kwip'),	
     (r'^comment/favourite/(?P<comment_id>\d+)/$',                    'comment.favourite_comment'),             
     (r'^follow/(?P<followee_username>\w+)$',                         'mykwips.follow_user'),
     (r'^follow_tweople/$',                                           'main.follow_tweople'),        
     (r'^friendships/add/(?P<friendship_offeree>\w+)/$',              'friend.add_friend'),
     (r'^friendships/remove/(?P<friendship_offeree>\w+)/$',           'friend.remove_friend'),                        
     (r'^unfollow_comments/(?P<quip_id>\d+)/$',                       'comment.unfollow_comments'),
     (r'^anon_unfollow_comments/(?P<foll_id>\d+)/$',                  'comment.anon_unfollow_comments'),                                                    
     (r'^im_notification/(?P<followee_username>\w+)/$',               'im_friendship_settings.im_notification'),                        
     (r'^check_username/$',                                           'main.checkusername'),
     (r'^check_email/$',                                              'main.checkemail'),
     (r'^check_password1/$',                                          'main.checkpassword1'),
     (r'^check_password2/$',                                          'main.checkpassword2'),
     (r'^invite_user/',                                               'main.invite_user'),
     (r'^invite_to_conversation/',                                    'main.invite_to_conversation'),
     (r'^invite_to_talk/',                                            'main.invite_to_talk'),
     (r'^activate_email/(?P<activation_code>\w+)/',		      'main.activate_secondary_email'),
     (r'^resend_activate_email/',		                      'main.resend_activate_secondary_email'),
     #(r'^([A-Za-z0-9_]+)/$',                                          'mykwips.mypage',{'quips_for':'all'}),
     #(r'^([A-Za-z0-9_]+)/kwips/$',                                    'mykwips.mypage',{'quips_for':'self'}),
     (r'^([A-Za-z0-9_]+)/kwip/(\d+)/$',                    'mykwips.one_kwip_page'),
     (r'^([A-Za-z0-9_]+)/kwips/page/(?P<page_num>\d+)/$',             'mykwips.mypage'),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/([A-Za-z]+)/(\d{2})/(\d{6})/([0-9]+)/$','mykwips.filtered_kwips_page',{'filter_by':'single'}),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/([A-Za-z]+)/(\d{2})/(\d{6})/$','mykwips.filtered_kwips_page',{'filter_by':'second'}),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/([A-Za-z]+)/(\d{2})/(\d{4})/$','mykwips.filtered_kwips_page',{'filter_by':'minute'}),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/([A-Za-z]+)/(\d{2})/(\d{2})/$','mykwips.filtered_kwips_page',{'filter_by':'hour'}),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/([A-Za-z]+)/(\d{2})/$',        'mykwips.filtered_kwips_page',{'filter_by':'date'}),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/([A-Za-z]+)/$',                'mykwips.filtered_kwips_page',{'filter_by':'month'}),
     (r'^([A-Za-z0-9_]+)/kwips/(\d{4})/$',                            'mykwips.filtered_kwips_page',{'filter_by':'year'}),
     (r'^([A-Za-z0-9_]+)/kwips/active/$',                             'mykwips.mypage',{'filter':'active','quips_for':'self'}),    
     (r'^([A-Za-z0-9_]+)/kwips/$',                                    'mykwips.mypage',{'filter':'','quips_for':'self'}),
     (r'^([A-Za-z0-9_]+)/kwips/recent/$',                                    'mykwips.mypage',{'filter':'','quips_for':'self'}),
     (r'^([A-Za-z0-9_]+)/comments/$',                                 'mycomments.main'),
     (r'^([A-Za-z0-9_]+)/profile/$',                                  'myprofile.main'),
     (r'^([A-Za-z0-9_]+)/kwip/delete/(?P<quip_id>\d+)/$',             'mykwips.delete_kwip'),
     (r'^([A-Za-z0-9_]+)/pvt_message/(?P<msg_id>\d+)/view/$',         'private_message.view'),
     (r'^([A-Za-z0-9_]+)/inbox/(?P<msg_id>\d+)/delete/$',             'private_message.delete_from_inbox'),
     (r'^([A-Za-z0-9_]+)/pvt_message/(?P<msg_id>\d+)/read/$',         'private_message.read'),
     (r'^([A-Za-z0-9_]+)/pvt_message/(?P<msg_id>\d+)/unread/$',       'private_message.unread'),
     (r'^([A-Za-z0-9_]+)/pvt_message/$',                              'private_message.pvt_message'),
     (r'^([A-Za-z0-9_]+)/buzz/$',                                     'buzz.buzz'),
     (r'^([A-Za-z0-9_]+)/bookmarks/$',                                'favorites.main',{'quips_for':'favourites'}),
     (r'^([A-Za-z0-9_]+)/favoritekwips/$',                            'favorites.main',{'quips_for':'favourites'}),
     (r'^([A-Za-z0-9_]+)/favoritecomments/$',                         'mycomments.favorites',),
     (r'^([A-Za-z0-9_]+)/dashboard/$',                                'mydashboard.dashboard'),
     (r'^([A-Za-z0-9_]+)/dashboard/account/$',                        'account_settings.account'),
     (r'^([A-Za-z0-9_]+)/dashboard/import/$',                         'mydashboard.import_ims'),
     (r'^([A-Za-z0-9_]+)/dashboard/invite/$',                         'mydashboard.invite_friends'),
     (r'^([A-Za-z0-9_]+)/dashboard/send_invites/$',                   'mydashboard.send_invites'),
     (r'^([A-Za-z0-9_]+)/dashboard/profile/$',                        'mydashboard.profile'),
     (r'^([A-Za-z0-9_]+)/dashboard/kwips_page/$',                     'mydashboard.kwips_page_settings'),
     (r'^([A-Za-z0-9_]+)/dashboard/acc_delete/$',                     'account_delete.main'),                        
     (r'^([A-Za-z0-9_]+)/inbox/sent/$',                               'inbox.sent'),
     (r'^([A-Za-z0-9_]+)/inbox/spam/$',                               'inbox.spam'),
     (r'^([A-Za-z0-9_]+)/messages/outbox/$',                          'inbox.sent'),
     (r'^([A-Za-z0-9_]+)/messages/outbox/(?P<msg_id>\d+)/$',          'private_message.view_outbox'),
     (r'^([A-Za-z0-9_]+)/messages/outbox/(?P<msg_id>\d+)/delete/$',   'private_message.delete_from_outbox'),                                                
     (r'^([A-Za-z0-9_]+)/messages/inbox/$',                           'inbox.list'),
     (r'^reply_pvt_msg/$',                                            'private_message.reply_pvt_msg'),                        
     (r'^([A-Za-z0-9_]+)/dashboard/account/stats/$',                   'fun.stats'),
     (r'^([A-Za-z0-9_]+)/followers/$',                                'listpage_views.myfollowers'),
     (r'^([A-Za-z0-9_]+)/following/$',                                'listpage_views.myfollowees'),
     (r'^([A-Za-z0-9_]+)/friends/$',                                  'listpage_views.myfriends'),
     (r'^([A-Za-z0-9_]+)/active/$',                                   'mykwips.mypage',{'filter':'active','quips_for':'all'}),
     (r'^([A-Za-z0-9_]+)/geo/$',                                      'mykwips.mypage',{'filter':'geo','quips_for':'all'}),
     (r'^([A-Za-z0-9_]+)/recent/$',                                          'mykwips.mypage',{'filter':'','quips_for':'all'}),
     (r'^([A-Za-z0-9_]+)/$',                                          'mykwips.mypage',{'filter':'','quips_for':'all'}),
)
